// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcojtx_t2M-218pt8lDe5gld1Oad1Ne2Q',
    appId: '1:602410551804:android:236835750aa70dcfd24a79',
    messagingSenderId: '602410551804',
    projectId: 'social-media-24fde',
    storageBucket: 'social-media-24fde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKUBZCazvnnSa0DFXT02Y8gZ_7CsP4Bkc',
    appId: '1:602410551804:ios:ac6757b61d45c92ad24a79',
    messagingSenderId: '602410551804',
    projectId: 'social-media-24fde',
    storageBucket: 'social-media-24fde.appspot.com',
    iosClientId: '602410551804-8b4p56p48amf8uv73l2a9etkt5t1bt0u.apps.googleusercontent.com',
    iosBundleId: 'com.media.social',
  );
}
